version: "3"

services:
  #Main Application
  stock_app:
    image: node:12.14-alpine
    working_dir: /usr/src/app
    container_name: stock_app
    depends_on:
      - stock_mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - .:/usr/src/app
    networks:
      - stock_app_network
    command: ./wait-for.sh stock_mongodb:$MONGO_PORT -- npm run dev

  #MongoDB Container Example
  stock_mongodb:
    image: mongo:4.2-bionic
    container_name: stock_mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "5101:$MONGO_PORT"
    volumes:
      - stock_mongodb_data:/data/db
    networks:
      - stock_app_network

networks:
  stock_app_network:
    external: true

volumes:
  stock_mongodb_data:
